type = "news"
title = "News"
description = "Recent updates and research milestones."

[[news]]
date = "Sep 2026"
content = 'Our \href{https://arxiv.org/pdf/2606.12956}{paper} was accepted to CoRL 2026!'

[[news]]
date = "Aug 2026"
content = 'I started my PhD at UMD!'

[[news]]
date = "Jun 2026"
content = 'I completed three years of mandatory military service at ADD. Grateful for my time there! 🥳'

[[news]]
date = "Jun 2026"
content = 'Our \href{https://xingxingzuo.github.io/MM-SpatialAI/assets/papers/submission-33-4d-latent-mapping-for-mobile-manipulation-policy-learning.pdf}{paper} received the \textcolor{red}{Best Paper Award} at the ICRA 2026 \href{https://xingxingzuo.github.io/MM-SpatialAI/}{Workshop on MM-SpatialAI}! 🎉'

[[news]]
date = "May 2026"
content = 'Our \href{https://openreview.net/pdf?id=QDdHFImjpH}{paper} was accepted to ICML 2026 \href{https://sites.google.com/view/icml-ctb/home}{Workshop on CTB}.'

[[news]]
date = "Mar 2026"
content = 'Our \href{https://arxiv.org/pdf/2603.13904}{paper} was accepted to CVPR 2026 \href{https://pvuw.github.io/}{Workshop on PVUW}.'
